name: 'Github Action Template'
description: 'Get started with Container actions'
author: 'Makuza Mugabo Verite'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
